// rootana_config.h
// generated by rootana Makefile Fri Sep 29 14:35:16 CEST 2023
//
#define HAVE_MIDAS 1
//#define MIDASSYS /home/petukhov/midas/midas
#define HAVE_LIBZ 1
#define HAVE_ROOT 1
//#define ROOTSYS /opt/root5
#define HAVE_ROOT_HTTP 1
#define HAVE_ROOT_XML 1
#define HAVE_THTTP_SERVER 1
#define HAVE_XMLSERVER 1
#define HAVE_LIBNETDIRECTORY 1
// end
